CREATE DATABASE dailyQuotes;
USE dailyQuotes;

CREATE TABLE quotes (
	quote_id INT PRIMARY KEY,
	quote TEXT NOT NULL,
    author TEXT
);

INSERT INTO quotes (id, quote, author) VALUES
(1, 'In this world the speaker is more important than their words.', '?'),
(2, 'And I’m working hard I be up while everybody sleep.', 'Tjay'),
(3, 'Your a good man with a good heart and it’s hard for a good man to be king.', 'Black Panther'),
(4, 'Am I worth it? Did I put enough work in?', 'Kendrick'),
(5, 'And I’m so dizzy, don’t know what hit me, but I’ll be alright.', 'J. Legend'),
(6, 'My heads underwater, but I’m breathing fine.', 'J. Legend'),
(7, 'Don’t get burned like cigarette.', 'Russ'),
(8, 'Dream big, I’ma get to the top.', 'Tjay'),
(9, 'Y’all ain’t think I would get what I got. But I stayed true to myself. No losing myself. Improving my self. I’m on the road to the riches.', 'Tjay'),
(10, 'Believe in yourself. Or that’s the place to start.', 'Arther'),
(11, 'Cash in and cash out. I am not looking for clout. I knew I would figure it out. I took the millionaire route.', 'Wunna'),
(12, 'They tried to set me up. They tried to get in my head and stuff.', 'Lee'),
(13, 'Well, we''ve made a massive amount of progress in this last year, haven''t we? Feels like a long journey. And I must say it''s been a pleasure, to watch you mature and grow… But you know, you can never stop learning about yourself.', 'ST'),
(14, 'I was down bad and they asked how I am I got up like a man and I said I’m alright.', 'Cee'),
(15, 'I met a lot of these rappers. And, and we ain’t got nothin in common.', 'Cee'),
(16, 'Keep on telling the young bulls grind don’t quit cause it’s all about timing.', 'Cee'),
(17, 'And I know it’s hard to find a way. But your bound to see brighter days.', 'Rod'),
(18, 'What made me great at some things made me lousy at others.', 'Lou'),
(19, 'Be proud of your dreams you should stand and shout.', 'ST'),
(20, 'I don’t know about you but I value my life. Cause imagine I die.', 'Cee'),
(21, 'I know it, I go through it don’t show it.', 'Meek'),
(22, 'I just wanna dance under the sunset, make nobody stop my enjoyment.', 'Joeboy'),
(23, 'I continue de struggle o, de double my hustle', 'Pquare'),
(24, 'It doesn’t cross anybodies mind, that what’s happening around them, is unacceptable in the eyes of God.', 'Drew'),
(25, 'Gotta kick back sometimes and wonder- how life would’ve been if I never did take them risks and would I have prospered?', 'Cee'),
(26, 'Praise the lord for the peace', 'ST'),
(27, 'Study hard is the best way to thank yourself. If you study hard today, you will enjoy the future.', 'Nandita Dasgupta'),
(28, 'Don’t cry. Don’t despair. Now is not the time for that.', 'Giyuu Tomioka'),
(29, 'For the longest time, I never understood what was so great about some dude walking on a rock. Cause in reality, the rockets are launched and flown by scientists and engineers.', 'Rikiel'),
(30, 'Almost there don’t give up now', 'Rihanna'),
(31, 'Ohhhhhh God, don’t let me go down, don’t let me go down', 'Burna'),
(32, 'I have to ignore all the pain in my body. Endure!', 'Kamado'),
(33, 'Everything could change, depends on what you do today. You gotta live with each decision that you choose to make', 'Polo'),
(34, 'Make them try their luck, my God go win.', 'Korede Bello'),
(35, 'With all the drive in the world swear you still need gas.', 'Big Sean'),
(36, 'As I’ve gotten older, I’ve realized what separates good from great. It’s how bad they want it', 'D'),
(37, 'You go bow for the result o', 'Burna'),
(38, 'Chop life. No let life chop you', '?'),
(39, 'One more day', 'Brian'),
(40, 'This is where you’ve gotta push past your limits. If you don’t, then your path ends here', 'Yami'),
(41, 'Wake up in the morning. Hallelujah!', 'Rema'),
(42, 'I swear I not go dull', 'Asake'),
(43, 'Morals won’t ever forget them', 'Tjay'),
(44, 'Told my n###as just ten toes, stand tall yeah', 'a boogie'),
(45, 'You are very gentle, I like you for that', 'Dad'),
(46, 'Dagonteee Dagontee, Dangonte still de find money o', 'Burna'),
(47, 'Humanity is greater than status', '?'),
(48, 'Stay in my lane play the game how the game go', 'Rod'),
(49, 'Na everybody go chop breakfast', 'Burna'),
(50, 'Who I be to come de sleep', 'Burna'),
(51, 'I got sisters and brothers to feed. I ain’t going out like no idiot, I’m a OG', 'Thugga'),
(52, 'F##k all this fame. I got trauma inside of my brain', 'Tjay'),
(53, 'Never gave a f###, I got me so I don’t need them', 'Rod'),
(54, 'They want me dead or alive, I’m just tryna survive', 'Jazz Cartier'),
(55, 'I’ll be there in a hurry when you call. Friends are there to catch you when you fall', 'Kirk Franklin'),
(56, 'Grateful for the sh## I got cause I come from a hard life', 'Tjay'),
(57, 'Thank God we ain’t on no T-shirts', 'Creek Boyz'),
(58, 'Gotta dominate. That’s the only way you gon get to the next level in anything in life', 'Deion Sanders'),
(59, 'Sometimes I’m weird. But it’s not sometimes, it’s always.', 'Alexis O’Malley'),
(60, 'Only way past is through', '?'),
(61, 'Man go fight for nonsense', 'Burna'),
(62, 'Sick and tired of it all take me far away', 'Burna'),
(63, 'Can’t be simple minded anymore or drown I gotta swim', 'Lee'),
(64, 'I know what to do.', 'Aaron Krause'),
(65, 'So preoccupied with grind and hustle, fight and tussle.', 'Knucks'),
(66, 'A lot of n###as b##ch made, stay in they feelings.', 'Superstar Pride'),
(67, 'When I was tryna work, n###as never tried to turn up. But when it’s time to turn up, everybody turns up.', 'ST'),
(68, 'Came out alive omo me I thank God', 'Rema'),
(69, 'Can’t worry about the past too much because we always tryna move forward in life. At every step we tryna just go to the next day', '?'),
(70, 'Can’t stop shooting cause that only means I stopped trying', 'Alexis'),
(71, 'If your not cheating you’re not trying', 'Eddie Guerrero'),
(72, 'Can get my feelings hurt today, I won’t give a f### tommorow', 'Glorilla'),
(73, 'Need to get myself together I’m a mess', '21'),
(74, 'You have to outwork everybody', 'D'),
(75, 'I know what’s right for me I got a plan to which I’m sticking', '?'),
(76, 'Who decides what’s normal', 'Marion Stokes'),
(77, 'Everybody in life has their own problems, I know for a fact I have mines', 'D'),
(78, 'Hustle is a decision and you can decide to out hustle everyone there.', 'zer0'),
(79, 'Keep it real I don’t f##k with y’all lil n###as, I can’t even fake it', 'baby'),
(80, 'Padi man, nobody like work. But you must hustle if you want chop', 'Ayra'),
(81, 'Love when I can still laugh through tough times', 'D'),
(82, 'Everybody else is playing chess and your in a field playing monopoly by yourself', '?'),
(83, 'I feel like I laugh too much for someone who’s not in a position to be laughing', 'D'),
(84, 'Lost friends but it’s my innocence I miss', 'ST'),
(85, 'Broke people should never laugh', 'Nicki'),
(86, 'At the time, it was bad, it was all in my mind. Cause in hindsight, it could\'ve been worse.', 'Cee'),
(87, 'I don\'t think that them man there serious', 'Cee'),
(88, 'A man stands up for himself, but a stronger man stands up for others', '?'),
(89, 'THERE IS NO TOMMOROW', 'Apollo Creed'),
(90, 'What happens when you get hit so hard, that you question your capability to keep on pushing? To God be the glory you gathered enough courage not to quit. But in the blink of eye, you got hit again. Only difference, it was 10x times harder. What happens next?', 'D'),
(91, 'There are no shortcuts if there were we would’ve found them and crammed in more work', 'O’Malley'),
(92, 'Someone is working harder than you', '?'),
(93, 'For the sake of someone other than yourself you can exert infinite strength.', 'Tokoito Yuichiro'),
(94, 'It ain’t personal, if it’s buisness. And that’s why we ain’t showing emotion.', 'Cee'),
(95, 'I am a tree standing tall in the sea, forever maintaining my peace.', 'D'),
(96, 'It is worth taking a hit for someone if it means you will shed less blood.', 'D'),
(97, 'The f##k they gon say now', 'Ice'),
(98, 'F##k all the n#￼#gas, get money. Motto', 'TiaCorine'),
(99, 'Everything won’t go to plan that’s not how it goes I’m afraid s##t happens', 'Cee'),
(100, 'Drop me in a jungle, tree to tree start swinging like Tarzan', 'Cee'),
(101, 'I got that dog in me for real. And it’s gonna come out when it needs to come out.', 'Scoot Henderson'),
(102, 'I’m tryna shake sh##.', 'D'),
(103, 'I can only fabricate the truth so much.', 'D'),
(104, 'Have I ever been wrong? I mean like, you know when it counts.', 'Pigeon mlm'),
(105, 'Working so hard every night and day And now we get the pay back. Trying so hard, saving up the paper Now we get to lay back.', '?'),
(106, 'When things bitter, she dey hang on. When things better, she dey thank God.', 'Omah Lay'),
(107, 'Sophomore year, that junk crazy. Before you know it we gonna be seniors.', 'D'),
(108, 'And that’s gonna be the end of it.', 'Ife'),
(109, 'Me I dey feel pain, but I move forward and I switch lanes. Because Odogwu no be nickname.', 'Burna'),
(110, 'I no go give into the pressure.', 'Joeboy'),
(111, 'I fell on my face, got up on my own.', 'Carti'),
(112, 'Oh to be stoic, to be resilient.', 'D'),
(113, 'Struggling what made us, hustling what saved us.', 'Rod'),
(114, 'If we don’t make mistakes we cannot learn what to work on.', 'Dr. Paula'),
(115, 'Fear what people think, if I’m happy might keep it quiet.', 'D'),
(116, 'If we are not monsters we’re food, and I could never be food.', 'Sully'),
(117, 'Been doubted so many times in my life, sometimes I surprise myself.', 'Knucks'),
(118, 'This is not a DIY project don’t try this I’m just fulfilling a promise.', 'Electroboom'),
(119, 'Thinking doesn’t overcome fear, action does.', '?'),
(120, 'We finally made it let’s pop us some bottles.', 'Baby'),
(121, 'You cross the finish line and taste victory… Do I regret that my hands tasted it first? Then my knees second. I’m on my knees shedding tears cause I been f##ked every year never knew if I would ever even make it.', 'D'),
(122, 'Couldn’t do no shining, cause I had to find me some paper first.', 'Rod'),
(123, 'When you feel like giving up, know your close.', 'ST'),
(124, 'I made that mistake and that’s on me. I just gotta own up to it like a f##king man.', 'D'),
(125, 'Collect my tears. You could fill a pool and breaststroke in it.', 'Cee'),
(126, 'The tides in the water are shifting. Change is approaching.', 'D'),
(127, 'I dun fell off, I dun gave up, I dun jumped back.', 'Rod'),
(128, 'Know how it feels to be broke of course. I’ve been down bad and I’ve been up town.', 'Cee'),
(129, 'Weight of the world on my shoulders I kept my head up.', 'DaBaby'),
(130, 'I no say e no easy, my brother. But still dey take am easy, my brother. As long as you are breathing, my brother. As long as you no sink inside water.', 'Burna'),
(131, 'My work had always taken up a lot of my time. I have more free time now, and over the years I’ve added a lot of hobbies to my life.', '?'),
(132, 'Keep it private till it’s permanent.', '?'),
(133, 'Had to give myself my own flowers.', 'ST'),
(134, 'I would say I’m finally here, but n##ga I’m trying to heal.', 'Rod'),
(135, 'I’m not tryna do this forever, just until I die, and then I quit.', 'Marty Meierotto'),
(136, 'I’m not sweet Estella, try as I might. I never was. I’m Cruella, born brilliant, born bad, and a little bit mad. I am not like her. I’m better.', 'Cruella'),
(137, 'There was a time where I mistakenly believed society operated the same way.', 'Kento Nanami'),
(138, 'I’m with Lockheed Martin. That is the one I want to hear.', 'Daddy'),
(139, 'I fought through it all. But that s##t hurt me severely.', 'Polo G'),
(140, 'I’ll be hanging on like I’m Mufasa.', 'Kidd lee'),
(141, 'I’m finding out what being royal’s all about.', 'Sofia'),
(142, 'I want to live a quiet life.', 'Kira Yoshikage'),
(143, 'If I keep it a buck, there was times when I thought that I wouldn’t survive.', 'Damzz'),
(144, 'BS in CS, truth is the transcript ain’t never seen em.', 'D'),
(145, 'BS in CS, wish the transcript never seen them.', 'D'),
(146, 'Starting selling white, we won’t sell it no more.', 'Meek'),
(147, 'I hear everything that is said. It don’t go over my head.', 'Cee'),
(148, 'Ruby grew up on her own she don’t have a problem with being alone.', 'Cee'),
(149, 'I talk to myself on my own I’m tapped.', 'Cee'),
(150, 'Underdogs with good intentions.', 'Kimya Dawson'),
(151, 'And still, I rise.', 'Maya Angelou'),
(152, 'Whatever you do today, you’ll have to sleep with tonight.', 'Aaron Tippin'),
(153, 'A reward for all those times I was stressed.', 'D'),
(154, 'Came a long way, still got a long way to go.', 'Cee'),
(155, 'That’s not the shape of my heart.', 'Sting'),
(156, 'Just got chased in the whip. I’m good, sang in the car to I’m a survivor.', 'ST'),
(157, 'Free roam is nice, but I think I’m gonna miss story mode.', '?'),
(158, 'Make you dey listen well because I no fit shout.', 'Burna'),
(159, 'I feel like if you\'re not delusional, you will not get far in life.', 'Ms London'),
(160, 'Neuroplasticity.', 'Scientists'),
(161, 'The day I don’t show up with my half that’s the day we’ll talk about closing this place.', 'Jimmy McGill'),
(162, 'Don’t get caught for pus, don’t die for nyash.', 'ST'),
(163, 'If you never allow yourself to experience the discomfort of failure, you may miss out on the opportunity to find the autonomy, and the intrinsic motivation necessary to be truly happy.', 'Daisy Day'),
(164, 'Embrace what you don’t know. Because you might discover that you can trust yourself in ways that you never thought were possible.', 'Daisy Day'),
(165, 'I’ve been becoming impatient, still I sit back and feel ease cause of patience. I think in time ima feel like I made it.', 'D'),
(166, 'Tough time don’t last, tough people do.', '?'),
(167, 'Where do you see this ending? With me on top, like always.', 'Saul Goodman'),
(168, 'Sometimes you gotta defy the odds and you can only do that by trusting your gut.', 'Polo g'),
(169, 'The nail that sticks out gets hammered down.', '?'),
(170, 'In mathematics it’s called a given.', 'Amrithya'),
(171, 'It was plan A now it’s plan B.', 'Young Dizz'),
(172, 'Inside a cage there’s nowhere to run, and I have to go forward.', 'Makunouchi'),
(173, 'We don’t say that we going through s##t but this life is a game and I’m flowing through it.', 'Jen Carter'),
(174, 'I might not be the smartest person there, at first.', 'Derrick Harris'),
(175, 'I knew my stuff and if I didn’t, I googled it.', 'Abiola Olamoyegun'),
(176, 'Why tap? Go sleep, go sleep.', 'Khabib'),
(177, 'This s##t doesn’t even give me any dopamine I just can’t stop.', 'Quinten'),
(178, 'I took loss on top of a loss and n###a I still ain’t quit the game.', 'nino'),
(179, 'My life in the hood soon comes to an end. B###h it’s the end of the beginning.', 'cench'),
(180, 'I couldn’t see light at the end of the tunnel but I believed.', 't'),
(181, 'Try everything once. if it sticks, it sticks. If it doesn’t, at least you tried.', '?'),
(182, 'Don’t fumble tryna 40 chess it.', 'Agent'),
(183, 'Cree-cree-creep in the changin\' room at school and teef from the kids that are privileged.', 'Cee'),
(184, 'What could only be described as a masterclass in delusional optimism.', 'Officially Opinionated'),
(185, 'On a mission full aware of all the odds.', 'Officially Opinionated'),
(186, 'You don’t need flowers when you know you put in your 10,000 hours.', 'Skepta'),
(187, 'More time I’m emotionless, It’s been a while now since I bust a tear.', 'Cee'),
(188, 'My girl ain\'t calm. She just numb to emotion, it\'s hard to affect her.', 'ST'),
(189, 'I accept say I change, me I no be same guy.', 'Bado'),
(190, 'I don’t even care about the prize, I just wanna be #1.', 'IG'),
(191, 'I’ve got paranoia there too much Jake’s, I’m not going through this again.', 'Cench'),
(192, 'Back then it was hard for me, these days I’m getting it easily.', 'Cench'),
(193, 'Can’t lie, man I ain’t the same brudda that I once was.', 'Skepta'),
(194, 'And I want it, I want my life so bad.', 'Sia'),
(195, 'I had to work so hard. I really wanted the jobs that I wanted, and I wouldn’t take no for an answer in the sweetest way.', 'Lea Salonga'),
(196, 'I’m not interested in status. I live alone.', 'Spider Rose'),
(197, 'I wouldn’t even say I get a sense of enjoyment, it’s almost like working.', 'Precious'),
(198, 'Get in your bag and get out your feelings. Show me what your worth.', 'Nemzzz'),
(199, 'Our main objective is to provide Wi-fi and that\'s all :)', 'Harshavardhan'),
(200, 'I might be alright but it ain’t okay.', 'Wunna'),
(201, 'The world has been gaslighting me for the past few years now, soon I will prove it.', 'D'),
(202, 'You just got dunked on, it can’t be your park.', 'MK'),
(203, 'You see I get money cause I go hard, but I want more money so I go harder.', 'Skepta'),
(204, 'Your fake fangs are only as sharp as they are thanks to years of training. I’ve possessed Godlike strength from the moment I was born.', 'Moz'),
(205, 'Hyoga! Damn you! To hell with you and your spear of sorcery!', 'Moz');